### ISSUE TITLE
obtain CT data used in the study

### ISSUE THREAD

**Issue by baibaidj** [neuro-ml/anchor-free-genant#1]
Hi. This is a pleasure to read your paper, which contains interesting and elegant ideas.  
While I try to download the public dataset mentioned in the paper from https://mosmed.ai/en/data-sets/ct_lungcancer_500, I did not get the email as expected. 
So, would you kindly point out some ways that I could get the data?

Thank you.

**Comment by maxme1** [comment]
Hi. Thank you!
Yes, unfortunately they changed the link. Here is the new one: https://mosmed.ai/en/datasets/mosmeddata-kt-s-priznakami-raka-legkogo-tip-viii/
By the way, we created easy to use interfaces for this an many more medical imaging datasets: https://github.com/neuro-ml/amid 
You might want to give it a try :wink:

**Comment by baibaidj** [comment]
Awesome. Thanks.

**Comment by maxme1** [comment]
Great. Feel free to open a new issue if you have any questions
