### ISSUE TITLE
obtain data annotations used in the study

### ISSUE THREAD

**Issue by GaoYiJing** [neuro-ml/anchor-free-genant#2]
Hi. This is a pleasure to read your paper, which contains interesting and elegant ideas.
I see that you have provided  keypoint annotations for each vertebrae.Is it possible to provide a description of the fracture classification (normal, mild, moderate, severe) of each vertebrae?

Thank you very much!

**Comment by maxme1** [comment]
Hello. I'm glad you enjoyed the paper! You can easily compute the severity of each vertebra based on its `"segments"` field. I've added the [classify_severity](https://github.com/neuro-ml/anchor-free-genant/blob/master/utils.py#L44) helper function just for that.

**Comment by GaoYiJing** [comment]
Thank you very much for your explanation. It turns out the code provides the annotations. Thank you!

**Comment by maxme1** [comment]
You're welcome!
